spring:
  application:
    name: arrangement-service

  r2dbc:
    url: r2dbc:postgresql://db:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    url: jdbc:postgresql://db:${DB_PORT}/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    change-log: classpath:db/changelog/changelog-master.yml

